### ISSUE TITLE
clone: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by sdarwin** [drone/autoscaler#108]
Running an autoscaler to test arm64 builds.   
AWS EC2 m6g.large
Sporadically seeing failed builds on newly launched instances:
```
clone: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

latest: Pulling from drone/git
Digest: sha256:091ecd02ee4ac5154fd76133c5055b2345a61cbc17182b00612df1fa7eef1510
Status: Downloaded newer image for drone/git:latest

Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
However, inot consistently, maybe 10% of the time.  Most of the time, no errors.

What comes to mind is to put a "sleep 1" or "systemctl restart docker" someplace.   A very small change.  

It looks like that is already present "[ systemctl, restart, docker ]"

Now trying a modification in drivers/internal/userdata/userdata.go .  Change 
```
  - path: /etc/docker/daemon.json
    content: |
      {
        "hosts": [ "0.0.0.0:2376", "unix:///var/run/docker.sock" ],
        "tls": true,
        "tlsverify": true,
        "tlscacert": "/etc/docker/ca.pem",
        "tlscert": "/etc/docker/server-cert.pem",
        "tlskey": "/etc/docker/server-key.pem"
      }
```
to
```
  - path: /etc/docker/daemon.json
    content: |
      {
        "hosts": [ "0.0.0.0:2376", "unix:///var/run/docker.sock" ],
        "containerd": "/run/containerd/containerd.sock",
        "tls": true,
        "tlsverify": true,
        "tlscacert": "/etc/docker/ca.pem",
        "tlscert": "/etc/docker/server-cert.pem",
        "tlskey": "/etc/docker/server-key.pem"
      }
```

Adding `"containerd": "/run/containerd/containerd.sock"` , based on this article https://stackoverflow.com/questions/68823645/what-is-purpose-of-the-switch-containerd-in-command-dockerd

I'll report back, if it eventually improves the condition.

**Comment by bradrydzewski** [comment]
I have not experienced this particular issue, however, the autoscaler supports providing custom cloud-init files, so you can test this without a code change:
https://autoscale.drone.io/configure/cloud-init/

**Comment by sdarwin** [comment]
Here are the results of the experiment, although mostly inconclusive. There were two variables to test:  
1. the above mentioned change in daemon.json
2. installing Ubuntu's docker.io versus Docker's docker-ce.  I had been using custom AMI's with docker.io, and it might have caused the problem.

- Switch to docker-ce.  Everything runs perfectly. Great.  
- Switch back to docker.io. Now everything is fine with that configuration also. In other words the issue has disappeared.  
- Change daemon.json. Still no errors.  

Perhaps for superstitous reasons then I will stay with docker-ce instead of docker.io.
No proof the change to daemon.json is required. From a logical basis, the autoscaler override is overriding this:
```
ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
```

Why remove the containerd.sock section?  Probably it should stay.  But no compelling evidence. 
 Sorry about the distraction, closing the issue.

**Comment by sdarwin** [comment]
Originally I read the first or second edit of your reply on this issue, only mentioning cloud-init.  Assuming that I had already read your answer I proceeded to run those tests. Posted the results.  In passing, review your answer again.    The package manager!!   That must be it.   The package manager must be stopping and/or restarting docker.  It would explain the error.
