### ISSUE TITLE
Creating a new instance on Hetznercloud fails with "image not found"

### ISSUE THREAD

**Issue by kolaente** [drone/autoscaler#99]
Since today, the autoscaler is unable to provision new instances on hetzner cloud. The drone cli tells me the ubuntu 16.04 image could not be found:

```
$ drone server info $(drone server ls)
Name: agent-wawR6snj
Address: 
Region:  
Size:    
State:   error
Error:   image 'ubuntu-16.04' not found (invalid_input)
```

My guess is hetzner deprecated the ubuntu 16.04 image.

I was able to fix this by setting the `DRONE_HETZNERCLOUD_IMAGE` environment variable to `ubuntu-20.04` - I think the default should be set to 20.04. I could send a PR if you'd accept one.

**Comment by eoinmcafee00** [comment]
Hi @kolaente 
If you want to raise a PR to fix this issue, it would be greatly appreciated. 
Thanks,
Eoin

**Comment by kolaente** [comment]
PR is up: https://github.com/drone/autoscaler/pull/100 @eoinmcafee00
